name: Build cloudflared on FreeBSD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build on FreeBSD
    steps:
    - uses: actions/checkout@v4
    
    - name: Test in FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: |
          pkg install -y git go gmake
          
    - name: Build cloudflared
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        run: |
          git clone https://github.com/cloudflare/cloudflared.git
          cd cloudflared
          make cloudflared
          cat /etc/os-release
          
          # Verify the binary was built
          file cloudflared
          ./cloudflared --version
          
          # Optional: Create artifacts
          mkdir -p artifacts
          cp cloudflared artifacts/
          
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cloudflared-freebsd
        path: cloudflared/artifacts/
